apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJrcHBtZXRhZGF0YXRlc3RpbmcuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImZhZjNiZGY2LTk5N2UtNGZkMy1hMjU5LWFjMTU4OGNhOGE3OSIsInBhc3N3b3JkIjoiWEpDOFF+RXk2bW94SzJtdldZU1hLRDY1bnVtYTRabloyR0V1UmFPNiIsImF1dGgiOiJabUZtTTJKa1pqWXRPVGszWlMwMFptUXpMV0V5TlRrdFlXTXhOVGc0WTJFNFlUYzVPbGhLUXpoUmZrVjVObTF2ZUVzeWJYWlhXVk5ZUzBRMk5XNTFiV0UwV201YU1rZEZkVkpoVHpZPSJ9fX0=
kind: Secret
metadata:
  name: acr-registry
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
