---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-insights-test
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-insights-test
      version: "<0.2.0"
      sourceRef:
        kind: HelmRepository
        name: app-insights-test-repo
        namespace: flux-system
  interval: 10m
  targetNamespace: flux-system
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: app-insights-test-repo
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m
  url: oci://ttl.sh/kaleb/charts
