---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-insights-test
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-insights-test
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: OCIRepository
        name: tts-sh-ocirepo
        namespace: flux-system
  interval: 1m0s
  targetNamespace: secure-only
  timeout: 10m
