apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
  - glob: "**"
  authorities:
    # either of the keys below is reasonable
  - name: signed-by-personal-cosign-key
    key:
      hashAlgorithm: sha256
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/d1CWZTcUW6AKfelUL5gSqEtIPTY
        2dYyiDBSlDbSqxmQulI/3y3hTocqHaImJrtn5ngb6aUbk7MTgFLhrAfx5Q==
        -----END PUBLIC KEY-----
  - name: signed-by-stefanprodan-cosign-key
    key:
      hashAlgorithm: sha256
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEST+BqQ1XZhhVYx0YWQjdUJYIG5Lt
        iz2+UxRIqmKBqNmce2T+l45qyqOs99qfD7gLNGmkVZ4vtJ9bM7FxChFczg==
        -----END PUBLIC KEY-----
#      attestations:
#      - name: custom-match-predicate
#        predicateType: https://cosign.sigstore.dev/attestation/v1
#        policy:
#          type: cue
#          data: |
#            predicateType: "https://cosign.sigstore.dev/attestation/v1"
#            predicate: "foobar key e2e test"
# We can also do something more dynamic, where we refer to the public key
# directly in Key Vault:
#    - key:
#        kms: azurekms://cosign-storage-kv2.vault.azure.net/cosignkey
