---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: custom-alpine-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: custom-alpine
      digest: sha256:a2c2a4fa48da2e3c1c7b3503d5b8a48c8f4a11db17575a8dc7f889e6eac9ca30 
      sourceRef:
        kind: HelmRepository
        name: custom-alpine-helm-repo
        namespace: flux-system
      verify:
        provider: cosign
        secretRef:
          name: cosign-public-key
  interval: 1m0s
  targetNamespace: secure-only
  timeout: 10m
