---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kpp-acr
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: latest
  secretRef:
    name: acr-registry
  url: oci://kppmetadatatesting.azurecr.io
