# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: nginx
#   namespace: flux-system
# spec:
#   chart:
#     spec:
#       chart: nginx-ingress
#       reconcileStrategy: ChartVersion
#       sourceRef:
#         kind: HelmRepository
#         name: nginx
#         namespace: flux-system
#       version: 1.0.1
#   targetNamespace: secure-only
#   interval: 1m0s
