---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policy-controller
  namespace: flux-system
spec:
  interval: 30m0s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: HelmRepository
    name: policy-controller
  targetNamespace: default
  timeout: 3m0s
  wait: true
