apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-controller
  namespace: system-policy
spec:
  interval: 30m
  chart:
    spec:
      chart: policy-controller
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: policy-controller
        namespace: system-policy
      interval: 1m
  values:
    webhook.replicaCount: 1


