apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  # -gr = git repository
  name: flux-controlled-tf-gr
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kalebpederson/flux-controlled-tf
  ref:
    branch: main
