apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: flux-controlled-tf
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./
  sourceRef:
    kind: GitRepository
    name: flux-controlled-tf-gr
    namespace: flux-system
  writeOutputsToSecret:
    name: flux-controlled-tf-secret
  runnerPodTemplate:
    spec:
      # includes the azure cli enabling azure authentication
      image: kppmetadatatesting.azurecr.io/tf-runner:1.7.2
      envFrom:
        - configMapRef:
            name: tf-runner-env-vars
        - secretRef:
            name: tf-runner-client-secret
