---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ttl-sh-ocirepo
  namespace: flux-system
spec:
  provider: generic
  interval: 5m0s
  secretRef:
    name: flux-acr-registry
  url: oci://ttl.sh/kaleb/98456748971649817436/charts
  ref:
    semver: "*"
  verify:
    provider: cosign
    secretRef:
      name: cosign-public-key
