apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-controller
  namespace: system-policy
spec:
  interval: 30m
  targetNamespace: system-policy
  releaseName: policy-controller
  install:
    disableWait: true
    crds: CreateReplace
  upgrade:
    disableWait: true
    crds: CreateReplace
  chart:
    spec:
      chart: policy-controller
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: sigstore
        namespace: flux-system
      interval: 60m
  values:
    webhook.replicaCount: 1
